### ISSUE TITLE
Proposition de tutoriels 

### ISSUE THREAD

**Issue by Ephrame** [KleeGroup/focus-docs#29]
Une page d'attribution de permissions/ droits avec : 
-  Une liste sélectionnable
-  Un form mixin

Des tutos sur les listes : 
- Une explication claire sur les différentes listes qui existent
- Type d'objets à renvoyer par le serveur 
- Bonne pratique avec le sort

**Comment by pierr** [comment]
- [ ] Un tuto par @DimitriMockelyn  sur je veux afficher une carte à côté des résultats de recherche. Avec utilisation du [connect](https://github.com/KleeGroup/focus-components/blob/develop/src/behaviours/store/connect.js)
