### ISSUE TITLE
Erreur dans le tutorial pour créer une liste d'administration

### ISSUE THREAD

**Issue by hnomichi** [KleeGroup/focus-docs#40]
Au paragraphe "Composant de Smartlist". Le composant en question demande une props "action", et le tuto nous fait passer la fonction "load" de l'action précédemment crée. Or chez moi cela a soulevé une erreur, le composant Smartlist attendait en fait l'objet qui contenait cette fonction "load".

**Comment by TomGallon** [comment]
@hnomichi merci Henri. Tu peux apporter la correction à la doc et pousser une pull request ?
merci beaucoup !
