### ISSUE TITLE
Icomoooooooooon ! 

### ISSUE THREAD

**Issue by Ephrame** [KleeGroup/focus-docs#59]
# Icomoon

Icomoon permet d'importer ses propres font à partir de fichiers svg. https://icomoon.io/app/#/select
## Transformation des svg en font

Il faut d'abord cliquer sur “import icons” dans le bandeau du haut. Vos svg s'ajouteront sur l'application web dans un nouveau sous-dossier que vous pouvez renommer.

Ensuite, il faut les sélectionner. Vous pouvez pour cela cliquer sur le bouton de menu de voter sous-dossier, puis “select all”.

Vous pouvez ensuite cliquer sur “Generate Font” tout en bas de l'écran.

Sur la nouvelle page, vous pouvez personnaliser vos icônes, puis cliquer sur download en bas de l'écran.
## Importer ses fonts dans son projet

Après avoir ajouté le contenu du dossier “fonts” dans votre dossier de font de votre projet, il faut ajouter le fichier style.css à ses feuilles de style.

Il ne reste plus qu'à importer ce fichier pour que les icônes soient accessibles.
## Utilisation des fonts dans son projet

Ajout d'une classe

Une première méthode et d'ajouter la classe correspondante aux noms des classes du fichier style.css là où on veut qu'un icône apparaît et style.css fera le reste.

Exemple: < span class=“icon-Home” />

Les boutons focus

Pour les utiliser sur les boutons focus, il faut ajouter dans les props du bouton:

icon: 'Litige'
iconLibrary: 'font-custom'
Autres méthodes

Il existe peut-être une autre méthode en utilisant directement les codes des icônes: “\e901”. Si vous utilisez cette méthode, ou même une autre, n'hésitez pas à compléter cette partie.
## Prévenir un problème de build

L'ajout ou la modification de font peut poser problème pour les builds: il faut dans ce cas suivre les étapes supplémentaires suivantes: Export des fonts

**Comment by TomGallon** [comment]
done in PR #60
